### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by wangbo123855842** [wangbo123855842/Learning#11]
<img width="300" alt="スクリーンショット 2020-04-27 19 41 55" src="https://user-images.githubusercontent.com/6970715/80368377-39ea2a00-88bf-11ea-9ced-a8f700788b9e.png">

# Ansible

Ansible是一个开源配置管理工具，可以使用它来自动化任务，部署应用程序实现IT基础架构。
Ansible可以用来自动化日常任务，比如，服务器的初始化配置、安全基线配置、更新和打补丁系统，安装软件包等。
<img width="428" alt="スクリーンショット 2020-04-28 14 08 21" src="https://user-images.githubusercontent.com/6970715/80551300-9a7b8300-89f5-11ea-8258-0e07def401a6.png">

#### Ansible架构相对比较简单，仅需通过SSH连接客户机执行任务即可
![8-460x243](https://user-images.githubusercontent.com/6970715/80551254-7ae45a80-89f5-11ea-9a42-d6ee7c46e64e.png)

## Ansible的优势

- **无需客户端**

与Chef、Puppet以及Saltstack（现在也支持**Agentless**方式salt-ssh）不同，**Ansible是无客户端Agent的，所以无需在客户机上安装或配置任何程序，就可以运行Ansible任务**。
由于Ansible不会在客户机上安装任何软件或运行监听程序，因此消除了许多管理开销，我们可以在即可上手使用Ansible管理服务器，**同时Ansible的更新也不会影响任何客户机**。

- **使用SSH进行通讯**

默认情况下，Ansible使用**SSH协议**在管理机和客户机之间进行通信。
可以使用**SFTP**与客户机进行安全的文件传输。
如果 SFTP 不可用，可在 ansible.cfg 配置文件中配置成 SCP 的方式

- **并行执行**

Ansible与客户机并行通信，可以更快地运行自动化任务。
默认情况下，forks值为5，可以按需，在配置文件中增大该值。

- **语法简单，维护方便**

定制剧本 **YAML no code**

## Ansible 概念

- **控制节点（Control node）**
**指安装了Ansible的主机** ，也叫Ansible服务器端,  管理机。 
Ansible控制节点主要用于**发布运行任务，执行控制命令**。
Ansible的程序都安装在控制节点上，控制节点需要安装Python和Ansible所需的各种依赖库

- **受控节点（Managed nodes）**
也叫**客户机**，就是想用Ansible执行任务的客户服务器

- **清单（Inventory）**
**受控节点的列表**，就是所有要管理的主机列表。

- **host文件**
**清单列表通常保存在一个名为host文件中**
在host文件中，可以使用IP地址或者主机名来表示具体的管理主机和认证信息
并可以根据主机的用户进行分组。缺省文件：`/etc/ansible/hosts`，可以通过-i指定自定义的host文件。

- **模块（Modules）**
**模块是Ansible执行特定任务的代码块**。比如：添加用户，上传文件和对客户机执行ping操作等。Ansible现在默认自带450多个模块。

- **任务（Task）**
**是Ansible客户机上执行的操作**。可以使用**ad-hoc**单行命令执行一个任务。

- **剧本（Playbook）**
**是利用YAML标记语言编写的可重复执行的任务的列表**
playbook实现任务的更便捷的读写和贡献。
在Github上有大量的Ansible playbooks共享

- **角色（roles）**
角色是Ansible 1.2版本引入的新特性，用于层次性、结构化地组织playbook。
roles能够根据层次型结构自动装载变量文件、tasks以及handlers等。

### Ansible目录结构
<img width="628" alt="スクリーンショット 2020-04-28 14 08 21" src="https://user-images.githubusercontent.com/6970715/80453315-93536700-895a-11ea-8d07-25477a364e8f.png">

## Ansible 安装

安装python
```
sudo yum install yum-util
sudo yum-builddep python
curl -O https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tgz
tar xf Python-3.5.0.tgz
cd Python-3.5.0
./configure
make
sudo make install
vi /etc/profile.d/python.sh
alias python='/usr/local/bin/python3.5'
chmod 755 /etc/profile.d/python.sh
source /etc/profile.d/python.sh
```
安装Ansible
```
sudo yum install ansible
```
Ansible默认是**通过SSH key和远程被控制主机进行通信**
当然我们可以SSH password来和远程主机进行通信。 
如果使用SSH KEY,则要将控制主机上的公钥放到被监控主机的/root/.ssh/authorized_keys文件中，
这种方式也是官方提倡的。毕竟直接使用密码存在一定的风险

在Ansible服务器上，生成公钥
```
ssh-keygen -t rsa
```
Ansible客户端的记录，添加到Ansible服务器的known_hosts
```
ssh-keyscan bob-ansible-c >> /root/.ssh/known_hosts
```
ssh在首次连接出现检查keys 的提示，通过设置避免
```
export ANSIBLE_HOST_KEY_CHECKING=False
```
将生成的秘钥发送到客户机
```
ssh-copy-id -i /root/.ssh/dreamarts.pm.pub root@bob-ansible-c
```

## Inventory文件

Ansible 可同时操作属于一个组的多台主机,组和主机之间的关系通过 inventory 文件配置. 
默认的文件路径为 /etc/ansible/hosts

### /etc/ansible/hosts 文件
```
[webservers]
foo.example.com
bar.example.com
one.example.com

[dbservers]
one.example.com
two.example.com
three.example.com
```

方括号[]中是组名, **用于对系统进行分类,便于对不同系统进行个别的管理**
**一个系统可以属于不同的组**,比如一台服务器可以同时属于 webserver组 和 dbserver组.
这时属于两个组的变量都可以为这台主机所用

端口号不是默认设置时,可明确的表示为
```
badwolf.example.com:5309
```
对于每一个 host , 你还可以选择连接类型和连接用户名
```
[targets]
localhost                        ansible_connection=local
other1.example.com     ansible_connection=ssh     ansible_ssh_user=root   ansible_ssh_pass=xxx
other2.example.com     ansible_connection=ssh     ansible_ssh_user=root   ansible_ssh_pass=xxx
```
配置后，测试连接
```
ansible all -m ping
```

### 主机变量
**分配变量给主机很容易做到** , 这些变量定义后可在 playbooks 中使用
```
[targets]
other1.example.com http_port=80 maxRequestsPerChild=808
other2.example.com http_port=303 maxRequestsPerChild=909
```

### 组的变量
也可以定义属于**整个组的变量**

```
[targets]
host1
host2

[targets:vars]
ntp_server=ntp.atlanta.example.com
proxy=proxy.atlanta.example.com
```

### 分文件定义 Host 和 Group 变量
**在 inventory 主文件中保存所有的变量并不是最佳的方式，还可以保存在独立的文件中**
这些独立文件与 inventory 文件保持关联. 不同于 inventory 文件(INI 格式)
这些独立文件的格式为 **YAML**

假设 inventory 文件的路径为
```
/etc/ansible/hosts
```
假设有一个主机名为 `bob-test`, 主机同时属于两个组,一个是 `web`, 另一个是`database`
那么以下配置文件(YAML 格式)中的变量可以为 `bob-test` 主机所用.
依次为 `web` 的组变量, `database`的组变量, `bob-test` 的主机变量
```
/etc/ansible/group_vars/database
/etc/ansible/group_vars/web
/etc/ansible/host_vars/bob-test
```
`/etc/ansible/group_vars/web`之中,可能类似这样的变量定义
```
---
ntp_server: acme.example.org
apache-version: 2.4
```

## Ad-Hoc命令

Ansible提供两种方式去完成任务,一是 ad-hoc 命令,一是写 Ansible playbook
前者可以解决一些简单的任务, 后者解决较复杂的任务.

比如在客户机上创建一个文件夹
```
ansible bob-ansible-c -a 'mkdir /root/test' -u root --sudo
↓
bob-ansible-c | SUCCESS | rc=0 >>
```
常用的Ansible命令行选项如下
```
-b，--become：特权方式运行命令。
-m：要使用的模块名称。
-a，--args：制定模块所需的参数。
-u：制定连接的用户名。
-h，--help显示帮助内容。
```

### 文件传输
```
ansible adservers -m copy -a "src=/root/test.txt dest=/root/test.txt.bk"
```
使用 file 模块可以做到修改文件的属主和权限
```
ansible adservers -m file -a "dest=/root/test.txt.bk mode=600"
ansible adservers -m file -a "dest=/root/test.txt.bk mode=600 owner=iseadmin group=iseadmin"
```

### Users and Groups
使用 user 模块可以方便的创建账户,删除账户,或是管理现有的账户
```
ansible all -m user -a "name=foo password=<crypted password here>"
```

### git 部署
直接使用 git 部署 webapp:
```
ansible adservers -m git -a "repo=https://stainless.dreamarts.co.jp/INSUITE/INSUITE-GENERAL.git dest=/home/DreamArts version=HEAD"
```

### Managing Services
安装httpd
```
ansible adservers -m yum -a "name=httpd state=present" -b
```
启动httpd服务只需要执行
```
ansible adservers -b -m service -a "name=httpd enabled=yes"
```
确认某个服务在所有的adservers上都已经启动
```
ansible adservers -m service -a "name=httpd state=started"
```
确认某个服务已经停止
```
ansible adservers -m service -a "name=httpd state=stopped"
```

## Ansible 配置文件

Ansible的一些的设置可以通过配置文件完成.在大多数场景下默认的配置就能满足大多数用户的需求
默认的位置 
```
/etc/ansible/ansible.cfg
```

## Playbooks
<img width="622" alt="スクリーンショット 2020-04-28 14 08 12" src="https://user-images.githubusercontent.com/6970715/80453888-b3cff100-895b-11ea-9e07-926aca85b2d2.png">

Playbooks 是 Ansible 的配置 , 部署 , 编排语言
他们可以被描述为一个**需要希望远程主机执行命令的方案, 或者一组IT程序运行的命令集合**
如果 Ansible 模块你是工作室中的工具,那么 playbooks 就是你设置的方案计划

Playbooks 与 Ad-Hoc 相比,是一种完全不同的运用 ansible 的方式

Playbooks 可用于**声明配置**,更强大的地方在于,在 playbooks 中**可以编排有序的执行过程**,
甚至于做到在多组机器间,来回有序的执行特别指定的步骤. **并且可以同步或异步的发起任务**

下面的工程里，有一些整套的playbooks,它们阐明了Playbooks的使用技巧
```
https://github.com/ansible/ansible-examples
```
**Playbooks 的格式是YAML**
每个playbook由一个或多个play组成。play的目标是将一组主机映射到任务中去。
每个play包含一个或多个任务，这些任务每次执行一次。

这里有一个 playbook,其中仅包含一个 play
```
---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest
  - name: write the apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=httpd state=started
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
```
包含多个play
```
- hosts: webservers
  remote_user: root
  tasks:
  - name: test connection
    ping:  
  - name: hostname
    raw: hostname
  - name: restart vsftpd
    service: name=vsftpd state=restarted enabled=yes 
- hosts: database
  remote_user: root
  tasks:
  - name: "start redis"
    service: name=redis state=started enabled=yes
```
所有的 YAML 文件(无论和 Ansible 有没有关系)开始行都应该是 ---. 
这是 YAML 格式的一部分, 表明一个文件的开始
YAML基本语法
- 大小写敏感
- 使用缩进表示层级关系
- 缩进不允许使用tab，只允许空格
- 缩进的空格数不重要，只要相同层级的元素左对齐即可

### 主机与用户
你可以为 playbook 中的每一个 play, 个别地选择操作的目标机器是哪些, 以哪个用户身份去完成要执行的步骤
```
---
- hosts: adservers
  remote_user: root
```
再者,在每一个 task 中,可以定义自己的远程用户
```
---
- hosts: webservers
  remote_user: root
  tasks:
    - name: test connection
      ping:
      remote_user: www
```
也支持从 sudo 执行命令
```
---
- hosts: webservers
  remote_user: yourname
  sudo: yes
```
同样的, 你可以仅在一个 task 中,使用 sudo 执行命令, 而不是在整个 play 中使用 sudo
```
---
- hosts: adservers
  remote_user: iseadmin
  tasks:
    - service: name=nginx state=started
      sudo: yes
```

### Tasks 列表
每一个 play 包含了一个 task 列表,
**一个 task 在其所对应的所有主机上执行完毕之后,下一个 task 才会执行**
有一点需要明白的是（很重要）,在一个 play 之中,所有 hosts 会获取相同的任务指令, 这是 play 的一个目的所在,也就是将一组选出的 hosts 映射到 task

在运行 playbook 时（从上到下执行）,如果一个 host 执行 task 失败,这个 host 将会从整个 playbook 的 rotation 中移除. 如果发生执行失败的情况,请修正 playbook 中的错误, 然后重新执行即可

下面是一种基本的 task 的定义,service  模块使用 key=value 格式的参数,
这也是大多数 module 使用的参数格式
```
tasks:
  - name: make sure apache is running
    service: name=httpd state=running
```
比较特别的两个 模块 是 command 和 shell ,它们不使用 key=value 格式的参数,而是这样
```
tasks:
  - name: disable selinux
    command: /sbin/setenforce 0
```
使用 command 模块 和 shell 模块 时,我们需要关心返回码信息
如果有一条命令,它的成功执行的返回码不是0, 你或许希望这样做
```
tasks:
  - name: run this command and ignore the result
    shell: /usr/bin/somecommand
    ignore_errors: True
```
假设在 `/etc/ansible/host_vars/bob-test` 那里定义了一个变量 vhost ,可以这样使用它
```
tasks:
  - name: create a virtual host file for {{ vhost }}
    template: src=somefile.j2 dest=/etc/httpd/conf.d/{{ vhost }}
```

### Handlers
**在发生改变时执行的操作**

当发生改动时,  notify actions 会在 playbook 的每一个 task 结束时被触发,而且即使有多个不同的 task 通知改动的发生, notify actions 只会被触发一次.
举例来说,比如多个 resources 指出因为一个配置文件被改动, 所以 apache 需要重新启动,但是重新启动的操作只会被执行一次.

这里有一个例子,当一个文件的内容被改动时 , 重启两个 services:
```
- name: template configuration file
  template: src=template.j2 dest=/etc/foo.conf
  notify:
     - restart memcached
     - restart apache
```
**notify 下列出的即是 handlers**

- Handlers 也是一些 task 的列表, 通过名字来引用
- 它们和一般的 task 并没有什么区别
- Handlers 是由通知者进行 notify, 如果没有被 notify, handlers 不会执行
- 不管有多少个通知者进行了 notify, 等到 play 中的所有 task 执行完成之后, handlers 也只会被执行一次
```
handlers:
    - name: restart memcached
      service:  name=memcached state=restarted
    - name: restart apache
      service: name=apache state=restarted
```
Handlers 最佳的应用场景是用来重启服务

如果你想立即执行所有的 handler 命令
```
tasks:
   - shell: some tasks go here
   - meta: flush_handlers
   - shell: some other tasks
```

### 执行一个 playbook
```
ansible-playbook playbook.yml
```
在执行一个 playbook 之前 , 想看看这个 playbook 的执行会影响到哪些 hosts , 你可以这样做:
```
ansible-playbook playbook.yml --list-hosts
```

## Playbook 角色(Roles) 和 Include 语句

当我们刚开始学习运用 playbook 时，可能会把 playbook 写成一个很大的文件，到后来可能你会希望这些文件是可以方便去重用的，所以需要重新去组织这些文件。

基本上，**使用 include 语句引用 task 文件的方法，可允许你将一个配置策略分解到更小的文件中**。
使用 include 语句引用 tasks 是将 tasks 从其他文件拉取过来。
因为 handlers 也是 tasks，所以你也可以使用 include 语句去引用 handlers 文件。

**Roles** 的概念来自于这样的想法：通过 include 包含文件并将它们组合在一起，组织成一个简洁、可重用的抽象对象。这种方式可使你将注意力更多地放在大局上，只有在需要时才去深入了解细节。

举个例子，如果我们要部署多个 wordpress 实例，我们可将所有的 wordpress task 写在一个 wordpress.yml 文件中， 然后像下面这样使用 wordpress.yml 文件
```
tasks:
  - include: wordpress.yml wp_user=timmy
  - include: wordpress.yml wp_user=alice
  - include: wordpress.yml wp_user=bob
```
wp_user 是传递给 wordpress.yml文件的参数
在wordpress.yml中这样使用
```
{{ wp_user }}
```
Ansible 支持另一种传递变量到 include files 的语法，这种语法支持结构化的变量
```
tasks:
  - include: wordpress.yml
    vars:
        wp_user: timmy
        some_list_variable:
          - alpha
          - beta
          - gamma
```
**Include 语句也可以用在 handlers 中**，比如，你希望定义一个重启 apache 的 handler， 你只需要定义一次，然后便可在所有的 playbook 中使用这个 handler。你可以创建一个 handlers.yml 文件如下
```
---
# this might be in a file like handlers/handlers.yml
- name: restart apache
  service: name=apache state=restarted
```
然后在你的主 playbook 文件中，在一个 play 的最后使用 include 包含 handlers.yml
```
handlers:
  - include: handlers/handlers.yml
```
**Include 语句也可用来将一个 playbook 文件导入另一个 playbook 文件**。
这种方式允许你定义一个顶层的 playbook，这个顶层 playbook 由其他 playbook 所组成。

举个例子
```
- name: this is a play at the top level of a file
  hosts: all
  remote_user: root
  tasks:
  - name: say hi
    tags: foo
    shell: echo "hi..."

- include: load_balancers.yml
- include: webservers.yml
- include: dbservers.yml
```
注意：当你在 playbook 中引用其他 playbook 时，不能使用变量替换。

### Roles

那怎样组织 playbook 才是最好的方式呢？简单的回答就是：**使用 roles** ! 
**Roles 基于一个已知的文件结构，去自动的加载某些 vars_files，tasks 以及 handlers**。
**基于 roles 对内容进行分组，使得我们可以容易地与其他用户分享 roles** 

例如， 一个项目的结构
```
site.yml
webservers.yml
fooservers.yml
roles/
   common/
     files/
     templates/
     tasks/
     handlers/
     vars/
     defaults/
     meta/
   webservers/
     files/
     templates/
     tasks/
     handlers/
     vars/
     defaults/
     meta/
```
一个 playbook 如下
```
---
- hosts: webservers
  roles:
     - common
     - webservers
```

- 如果 roles/common/tasks/main.yml 存在, 其中列出的 tasks 将被添加到 play 中
- 如果 roles/common/handlers/main.yml 存在, 其中列出的 handlers 将被添加到 play 中
- 如果 roles/common/vars/main.yml 存在, 其中列出的 variables 将被添加到 play 中
- 如果 roles/common/meta/main.yml 存在, 其中列出的 “角色依赖” 将被添加到 roles 列表中
- 复制的静态文件都放在files目录下，用来存放由copy模块或script模块调用的文件
- 模板文件的都放在templates目录下，template模块会自动在此目录中寻找模板文件

#### 角色依赖
角色依赖 使你可以自动地将其他 roles 拉取到现在使用的 role 中。
角色依赖 保存在 roles 目录下的 meta/main.yml 文件中。
这个文件应包含一列 roles 和 为之指定的参数

下面是在 roles/myapp/meta/main.yml 文件中的示例
```
---
dependencies:
  - { role: common, some_parameter: 3 }
  - { role: apache, port: 80 }
  - { role: postgres, dbname: blarg, other_parameter: 12 }
```

### ansible roles总结

1、编写任务(task)的时候，里面不需要写需要执行的主机，单纯的写某个任务是干什么的即可，装软件的就是装软件的，启动的就是启动的。单独做某一件事即可，最后通过main.yml将这些单独的任务安装执行顺序include进来即可，这样方便维护且一目了然。

2、定义变量时候直接安装k:v格式将变量写在vars/main.yml文件即可，然后task或者template直接调用即可，会自动去vars/main.yml文件里面去找。

3、定义handlers时候，直接在handlers/main.yml文件中写需要做什么事情即可，多可的话可以全部写在该文件里面，也可以像task那样分开来写，通过include引入一样的可以。在task调用notify时直接写与handlers名字对应即可。

4、模板文件一样放在templates目录下即可，task调用的时后直接写文件名字即可，会自动去到templates里面找。

## 变量

- 在playbook中定义变量

在playbook中,可以直接定义变量
```
- hosts: webservers
  vars:
    http_port: 80
```

- 在文件和role中定义变量
变量也可以通过文件包含在playbook中, 该变量可以作为或者不作为“Ansible Role”的一部分
使用role是首选,因为它提供了一个很好的组织体系.

### 使用变量: 关于Jinja2
Ansible允许你使用**Jinja2模板系统**在playbook中**引用变量**
通过 `{{ vars }}` 来引用变量
```
My amp goes to {{ max_amp_value }}
```

### 变量文件分割
使用外部的变量文件
```
---
- hosts: all
  remote_user: root
  vars:
    favcolor: blue
  vars_files:
    - /vars/external_vars.yml

  tasks:

  - name: this is just a placeholder
    command: /bin/echo foo
```
每个变量文件的内容是一个简单的YAML文件
```
---
# in the above example, this would be vars/external_vars.yml
somevar: somevalue
password: magic
```

### When 语句
有时候用户有可能需要某一个主机越过某一个特定的步骤.这个过程就可以简单的像在某一个特定版本的系统上 少装了一个包一样或者像在一个满了的文件系统上执行清理操作一样. 这些操作在Ansible上,若使用`when`语句都异常简单
```
tasks:
  - command: /bin/false
    register: result
    ignore_errors: True
  - command: /bin/something
    when: result|failed
  - command: /bin/something_else
    when: result|success
  - command: /bin/still/something_else
    when: result|skipped
```
有些时候你得到一个返回参数的值是一个字符串,并且你还想使用数学操作来比较它,那么你可以执行一下操作
```
tasks:
  - shell: echo "only on Red Hat 6, derivatives, and later"
    when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 6
```
如果一个变量不存在,你可以使用Jinja2的`defined`命令跳过或略过
```
tasks:
    - shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined

    - fail: msg="Bailing out. this play requires 'bar'"
      when: bar is not defined
```
`when`he`with_items`
```
tasks:
    - command: echo {{ item }}
      with_items: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5
```

### 注册变量
经常在playbook中,存储某个命令的结果在变量中,以备日后访问是很有用的
这个  `register` 关键词决定了把结果存储在哪个变量中.结果参数可以用在模版中,动作条目,或者 when 语句
```
- name: registered variable usage as a with_items list
  hosts: all

  tasks:

      - name: retrieve the list of home directories
        command: ls /home
        register: home_dirs

      - name: add home dirs to the backup spooler
        file: path=/mnt/bkspool/{{ item }} src=/home/{{ item }} state=link
        with_items: home_dirs.stdout_lines
        # same as with_items: home_dirs.stdout.split()
```

### 标准循环
为了保持简洁,重复的任务可以用以下简写的方式
```
- name: add several users
  user: name={{ item }} state=present groups=wheel
  with_items:
     - testuser1
     - testuser2
```
如果你在变量文件中或者 vars 区域定义了一组YAML列表, 你也可以这样做
```
with_items: "{{ somelist }}"
```
with_items 用于迭代的条目类型不仅仅支持简单的字符串列表，还可以是一个哈希列表
```
- name: add several users
  user: name={{ item.name }} state=present groups={{ item.groups }}
  with_items:
    - { name: 'testuser1', groups: 'wheel' }
    - { name: 'testuser2', groups: 'root' }
```

### 嵌套循环
循环也可以嵌套
```
- name: give users access to multiple databases
  mysql_user: name={{ item[0] }} priv={{ item[1] }}.*:ALL append_privs=yes password=foo
  with_nested:
    - [ 'alice', 'bob' ]
    - [ 'clientdb', 'employeedb', 'providerdb' ]
```

### 对哈希表使用循环
假如你有以下变量
```
---
users:
  alice:
    name: Alice Appleworth
    telephone: 123-456-7890
  bob:
    name: Bob Bananarama
    telephone: 987-654-3210
```
你想打印出每个用户的名称和电话号码.你可以使用 with_dict 来循环哈希表中的元素
```
tasks:
  - name: Print phone records
    debug: msg="User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
    with_dict: "{{users}}"
```

## INSUITE自動バージョンアップ　Ansible導入（仮案）

![6608c680-89f7-11ea-9e83-7c6419946c92](https://user-images.githubusercontent.com/6970715/80554677-7bceb980-8a00-11ea-9efd-c887420de1ef.png)
Chefに比べて、Ansibleは以下のメリットがあります。
- 設定ファイルがシンプル
- 使いやすい YAML no Code
- 管理対象サーバへのエージェントソフトウェアインストール不要

その中で、管理対象サーバ（INSUITE管理サーバ）で、エージェントソフトウェアインストール不要は一番利点です。

DCSユーザさんの管理サーバ、IP・ドメインを事前に `/etc/ansible/hosts` に登録します。
Ansibleサーバと、各管理サーバは、SSH KEYで接続は推薦します。
※ 事前に ssh-keygen コマンドでSSHの公開鍵と秘密鍵作成

#### /etc/ansible/hosts 文件
```
[dcs_user_1]
dcs_user_1.insuite.co.jp ansible_connection=ssh     ansible_ssh_user=root   ansible_ssh_pass=xxx

[dcs_user_2]
dcs_user_2.insuite.co.jp ansible_connection=ssh     ansible_ssh_user=root   ansible_ssh_pass=xxx
```

#### Ansibleサーバの構成想定
<img width="1005" alt="スクリーンショット 2020-04-29 9 47 04" src="https://user-images.githubusercontent.com/6970715/80554683-838e5e00-8a00-11ea-8855-f925277fa679.png">

Ansible サーバへautoVersionUp.shをデプロイ想定。
autoVersionUp.shの利用シーンは、
例えば、dcs_user_1に対して、2020/05/01 14:00:00でバージョンアップしたい場合
以下のコマンド発行します。
```
./autoVersionUp.sh --target dcs_user_1 --from V3.5.2  --to V3.5.5   --date 2020/05/01 14:00:00
```
autoVersionUp.sh内部で、バージョンアップは、どのステップが必要を計算します。
該当お客様に対して、dcs_user_1.yml（Playbook）を作成します、該当Playbookは、適当のRolesをIncludeします。

- dateが設定する場合
Ansible サーバのcrontabを登録します。
該当時点で、Ansible サーバで、以下のコマンド発行して、バージョンアップを行います。
```
ansible-playbook dcs_user_1.yml
```

- dateが設定しない場合
即時、Ansible サーバで、以下のコマンド発行して、バージョンアップを行います。
```
ansible-playbook dcs_user_1.yml
```

### メリット
1. バージョンアップ操作処理は、Ansible サーバのみで実施すれば十分。
2. 定時バージョンアップ可能
3. 全部のDCSユーザのバージョンアップ情報を一元管理できる
4. 各Clientサーバの情報を見えます。
5. INSUITE管理サーバは、エージェントソフトウェアインストール不要

### デメリット（前提条件）
1. Ansible サーバと、各INSUITE管理サーバで、SSH通信できる設定必要
