### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by wangbo123855842** [wangbo123855842/Learning#35]
<img width="400" alt="スクリーンショット 2020-10-10 21 15 00" src="https://user-images.githubusercontent.com/6970715/95656008-e9e5e380-0b3d-11eb-91a7-8c2f86fc6a10.png">

## Compose 概述

Docker Compose 是用来管理你的容器的，有点像一个容器的管家，想象一下当你的 Docker 中有成百上千的容器需要启动，如果一个一个的启动那得多费时间。

**Docker Compose 是用于定义和运行多容器 Docker 应用程序的工具**。通过 Docker Compose ，您可以使用YAML文件来配置应用程序的服务。然后，使用一个命令，就可以从配置中创建并启动所有服务。

但是 **Docker-Compose 只能管理当前主机上的 Docker**，也就是说**不能去启动其他主机上的 Docker 容器**。

Docker 是容器技术的核心、基础，Docker Compose 是一个基于 Docker 的单主机容器编排工具，
功能并不像 Docker Swarm 和 Kubernetes 是基于 Docker 的跨主机的容器管理平台那么丰富。

简单点说，**Docker Compose是单机管理Docker的，Kubernetes是多节点管理Docker的**。

## 使用 Compose 过程

1. 定义应用的 Dockerfile 

2. 定义组成应用程序的服务，docker-compose.yml

3. 执行 `docker-compose up`，启动你的各个应用服务

## Compose 安装

Docker Desktop for Mac 中已经包含了 Docker Compose，无需单独安装。

测试安装是否成功
```
docker-compose --version
docker-compose version 1.27.4, build 01110ad01
```

## Compose 入门

- 编写 Dockerfile 文件

创建一个 web 应用的 Dockerfile 文件，用来构建这个 web 应用的镜像。
这个 web 应用使用了 redis 服务，应用程序网络上的 redis 容器的主机名是 redis。我们为Redis使用默认端口6379。

- 编写 docker-compose.yml 文件

Docker Compose 运行目录下的所有文件（docker-compose.yml）**组成一个工程**
**一个工程包含多个服务**，**每个服务中定义了容器**运行的镜像、参数、依赖，**一个服务可包括多个容器实例**。

该 Compose 文件定义了两个服务：web 和 redis。

```
version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
```
该 web 服务使用从 Dockerfile 当前目录中构建的映像。
然后，它将容器和主机绑定到暴露的端口5000。
该 redis 服务使用从 Docker Hub 的公共 Redis 镜像。

- 运行服务

```
docker-compose up
```
若以后台方式运行
```
docker-compose up -d
```

- 停止服务

```
docker-compose down
```

- 重新构建并运行服务

执行 `docker-compose up`  会自动构建镜像并使用镜像启动容器。

- 查看当前的运行

```
docker-compose ps

Name                 Command            State       Ports
-------------------------------------------------------------------
composetest_redis_1   /usr/local/bin/run         Up
composetest_web_1     /bin/sh -c python app.py   Up      5000->5000/tcp
```

## Compose 常用命令

- **ps**

```
docker-compose ps
```
列出所有运行容器

- **logs**

```
docker-compose logs
```
查看服务日志输出
```
docker-compose logs  nginx      查看nginx的日志 
docker-compose logs -f nginx    查看nginx的实时日志
```

- **port**

查看绑定的公共端口
下面命令可以输出 web 服务 5000 端口所绑定的公共端口
```
docker-compose port web 5000
```

- **build**

```
docker-compose build
```
构建或者重新构建服务

- **start**

```
docker compose start web
```
启动指定服务已存在的容器

- **stop**

```
docker-compose stop web
```
停止已运行的服务的容器

- **rm**

```
docker-compose rm web
```
删除指定服务的容器

- **up**

```
docker-compose up
```
构建、启动容器

- **kill**

```
docker-compose kill web
```
通过发送 SIGKILL 信号来停止指定服务的容器

- **pull**

```
docker-compose pull
```
下载镜像

- **scale**

```
docker-compose up --scale web=3 -d
```
设置指定服务运气容器的个数，以 `service=num` 形式指定
我们使用 docker-compose ps ，能够查看到此时三个 web 的容器都开启了5000端口。

搭配 HAProxy，实现单机版的负载均衡

<img width="600" alt="スクリーンショット 2020-10-11 11 21 59" src="https://user-images.githubusercontent.com/6970715/95669500-03c20d80-0bb4-11eb-86bd-eee4844a7ae9.png">

- **run**

```
docker-compose run web env
```
在一个服务上执行一个命令，比如，上面的命令，查看哪些环境变量可用于 web服务

- **down**

```
docker-compose down
```
 删除所有容器，镜像

- **restart**

```
docker-compose restart web
```
重新启动 web 容器

- **pause**

```
docker-compose pause
```
暂停服务

```
docker-compose pause web
```
暂停 web 服务

- **unpause**

```
docker-compose unpause
```
恢复服务

## docker-compose.yml 属性

- **version**：指定 docker-compose.yml 文件的写法格式

- **services**：多个容器集合

- **image**：指定镜像

- **build**

配置构建时，**Compose 会利用它自动构建镜像**
该值可以是一个路径
```
build: ./dir
```
也可以是一个对象，**用于指定 Dockerfile 参数**
```
build:
    context: ./dir
    dockerfile: Dockerfile
    args:
        buildno: 1
```

- **command**

覆盖容器启动后默认执行的命令
```
command: bundle exec thin -p 3000
```
该命令也可以是一个列表
```
command: ["bundle", "exec", "thin", "-p", "3000"]
```

- **environment**：环境变量配置

```
environment:
    RACK_ENV: development
    SHOW: 'ture'
```

- **env_file**

从文件中获取环境变量，可以指定一个文件路径或路径列表，其优先级低于 environment 指定的环境变量

```
env_file: .env
---------------
env_file:
    - ./common.env
```

- **ports**

暴露容器端口到主机的任意端口或指定端口

```
ports:   # 暴露端口信息  - " 宿主机端口:容器暴露端口 "
- "8763:8763"
- "8763:8763"
```

- **expose**

expose 暴露容器给 link 到当前容器的容器

```
expose:
- "3000"
- "8000"
```

以上指令将当前容器的端口 3000 和 8000 暴露给 link 到本容器的容器。
和 ports 的区别是，expose 不会将端口暴露给主机。

- **links**

链接到其它服务的中的容器（SERVICE：ALIAS)

```
web:  # 指定服务名称:别名 
  links:
   - db:database
```
这样 Web 服务就可以使用 db 或 database 作为 hostname 访问 db 服务了。

使用的别名将会自动在服务容器中的/etc/hosts里创建。
```
172.12.2.186  db
172.12.2.186  database
```

- **container_name**

```
container_name: "isx-mysql"
```
自定义容器名

- **external_links**

在使用 Docker 过程中，我们会有许多单独使用 docker run 启动的容器。
为了使 Compose 能够连接这些不在 docker-compose.yml 中定义的容器，我们需要一个特殊的标签，就是 external_links。
**它可以让 Compose 项目里面的容器连接到那些项目配置外部的容器**。

```
external_links:
 - redis_1
 - project_db_1:mysql
```

- **volumes**

挂载一个目录 或者 一个已存在的数据卷容器。
可以直接使用 [HOST:CONTAINER] 这样的格式，或者使用 [HOST:CONTAINER:ro] 这样的格式。后者对于容器来说，数据卷是只读的，这样可以有效保护宿主机的文件系统。

```
volumes:

  // 只是指定一个路径，Docker 会自动在创建一个数据卷（这个路径是容器内部的）。
  - /var/lib/mysql
 
  // 使用绝对路径挂载数据卷
  - /opt/data:/var/lib/mysql
 
  // 以 Compose 配置文件为中心的相对路径作为数据卷挂载到容器。
  - ./cache:/tmp/cache
 
  // 使用用户的相对路径（~/ 表示的目录是 /home/<用户目录>/ 或者 /root/）。
  - ~/configs:/etc/configs/:ro
 
  // 已经存在的命名的数据卷。
  - datavolume:/var/lib/mysql
```

##  Compose 网络设置

默认情况下，Compose 会为我们的应用创建一个网络，**服务的每个容器都会加入该网络中**。
这样，容器就可被该网络中的其他容器访问，不仅如此，该容器还能以服务名称作为 hostname 被其他容器访问。

docker-compose 中未显式声明，会生成默认的网络，比如
```
version: "3.4"
services:
  redis-web:
    image: redis-web:1.0
    container_name: redis-web
    restart: always
    environment:
      REDIS_HOST: redis-app
    ports:
      - 8001:8001
    depends_on:
      - redis-app
  redis-app:
    image: redis:latest
    container_name: redis-app
    restart: always
```

启动的容器会被加入 myapp_default 中，其中 myapp 为 **docker-compose 的父文件夹名**。
```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
be43cf4b2125       myapp_default        bridge              local
```

**使用 networks 关键字自定义网络**。比如
```
version: '3.4'
services:
  web-1:
    image: redis-web:1.0
    container_name: web1
    networks:
      - front
      - back
  redis:
    image: redis
    container_name: redisdb
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
    driver_opts:
      foo: "1"
      bar: "2"
```

这样就自定义，创建了网络
```
docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
ca9419193d95        network-test_back    bridge              local
7c38ab9beba4        network-test_front   bridge              local
```

## 控制启动顺序

**可以使用 depends_on 选项控制服务启动和关闭的顺序**。

比如，下面这样，web 会等到 redis 和 db 两个服务启动之后再启动。
```
version: '3'
services:
  web:
    build: .
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```
