### ISSUE TITLE
CI/CD - Github Actions

### ISSUE THREAD

**Issue by wangbo123855842** [wangbo123855842/Learning#7]
<img width="500" alt="スクリーンショット 2020-04-16 13 59 31" src="https://user-images.githubusercontent.com/6970715/79419990-8776b500-7fea-11ea-88bf-fe8867c887c4.png">

# github Action

GitHubが2019年11月、新機能「GitHub Actions」を正式に公開した。GitHub上のリポジトリやイシューに対するさまざまな操作をトリガーとしてあらかじめ定義しておいた処理を実行できる機能で、**今まで外部サービスとの連携が必要だった自動テストや自動ビルドなどがGitHubだけで実現できるようになる**。

## GitHubだけでCI/CD的な機能を実現できる「GitHub Actions」

ソフトウェア開発におけるさまざまな工程を**自動化**するような技術の開発や普及が進んでいる。その1つに、CI（Continuous Integration、継続的インテグレーション）やCD（Continuous Delivery、継続的デリバリー）と呼ばれるものがある。**CIはソフトウェアのビルドやテストを自動化して頻繁に実行することでソフトウェアの品質向上や開発効率化を目指す手法で、CDはCIに加えてリリースやデプロイまでも自動化する手法だ。**

CIやCDに関する技術やソフトウェアについては過去にもあったが、どれも基本的にはGitなどのバージョン管理システムと組み合わせての利用が前提となっている。たとえば、多くのCI/CDツールでは**リポジトリへのプッシュやマージ、プルリクエストなどをトリガーにしてさまざまな処理を自動実行できるようになっている**。最近ではクラウド型のCI/CDサービスも登場しており、こういったサービスではGitHubリポジトリとCI/CDサービスを関連付ける設定を行うだけで簡単にCI/CDが利用できるようになっている。

こういったCI/CDに関連する機能をGitHubが自ら実装したものが、今回紹介する「GitHub Actions」という機能だ。GitHub Actionsは2018年に発表された機能で、しばらくは利用申請をした一部のユーザーのみが利用できる機能だったが、2019年11月には正式版の機能となり、現在はGitHubを利用するすべてのユーザーが特に申請や手続きを行うことなく利用できるようになっている。

## GitHub Actionsでできること

GitHub Actionsは、ほかのCI/CDツールと同様、リポジトリに対する**プッシュ**や**プルリクエスト**といった操作、もしくは**指定した時刻になるといったイベント**をトリガーとして、あらかじめ定義しておいた処理を実行する機能だ。たとえばリポジトリにコミットが行われた際に特定の処理を実行したり、毎日決まった時刻に特定の処理を実行したりする、といったことを実現できる。
### これらの処理はGitHubが提供するサーバー上に用意された仮想マシン内で実行できるため、ユーザーが独自にサーバーなどを準備する必要はない点が最大のメリットだ。

仮想マシン上で利用できるOSとしては、Linux（Ubuntu）およびWindows、macOSに対応している。**仮想マシン上にはOSだけでなく、さまざまな言語のコンパイラや各種ランタイム、主要ライブラリといったソフトウェア開発環境も標準でインストールされている。** さらに、sudoコマンドを使ってroot権限でコマンドを実行させることもできる。つまり、一般的なサーバー上で実行できるほとんどの処理を実行できるわけだ。利用規約によって禁止されている処理ですら（アカウント凍結といったペナルティなどを受ける可能性は高いが）実行自体は可能だ。

また、特別なハードウェアが必要な場合や、後述する制約を回避したい場合、また仮想マシン内でなく実マシン上で実行させたいといった場合は、ユーザーのサーバー上で処理を実行させることもできるようになっている。

## ActionとWorkflow

GitHub Actionsでは、実行する処理とその処理を実行する条件を定義したものを「Workflow（ワークフロー）」と呼ぶ。**ワークフローはYAML形式で記述し、リポジトリ内の.github/workflowsディレクトリ内に保存することで実行できるようになる。**

ワークフロー内では、**シェル経由で任意のコマンドを実行できるほか、「Action（アクション）」という、あらかじめ定義済みの処理を呼び出せるようになっている。**

**たとえばGitHubの提供しているCheckoutというActionでは、指定したリポジトリからソースコードをチェックアウトする処理が定義されている。** プライベートリポジトリからチェックアウトを行う場合は認証処理などが必要となるが、このActionを利用すれば数行の設定を記述するだけで簡単にチェックアウトを実行できる。そのほか、GitHubが提供しているActionとしては、下表のものがある。

<img width="902" alt="スクリーンショット 2020-04-16 14 00 20" src="https://user-images.githubusercontent.com/6970715/79420037-a117fc80-7fea-11ea-9d72-19ea7bbfba77.png">

**https://github.com/marketplace?before=Y3Vyc29yOjIx&type=actions**

公開しているActionsを使用する
<img width="611" alt="スクリーンショット 2020-04-16 14 01 19" src="https://user-images.githubusercontent.com/6970715/79420101-c60c6f80-7fea-11ea-93d2-7fb37b54358d.png">

これ以外にも、**ユーザーが独自にActionを作成することも可能だ**。ActionについてはNode.jsで記述できるほか、**Dockerコンテナを利用して任意の処理を実行させるようなものも作成できる**。

GitHub公式のActionについては、個別リポジトリ（actions/）で参照できる
**https://github.com/actions**

各部分の説明
<img width="1251" alt="スクリーンショット 2020-04-16 14 01 52" src="https://user-images.githubusercontent.com/6970715/79420163-ed633c80-7fea-11ea-98db-ae981713d699.png">

**例**
<img width="1298" alt="スクリーンショット 2020-04-16 14 02 01" src="https://user-images.githubusercontent.com/6970715/79420173-f8b66800-7fea-11ea-97db-1fa503ce95b2.png">
<img width="1314" alt="スクリーンショット 2020-04-16 14 02 09" src="https://user-images.githubusercontent.com/6970715/79420181-fe13b280-7fea-11ea-8ce9-68d9cbf0183c.png">
<img width="889" alt="スクリーンショット 2020-04-16 14 02 17" src="https://user-images.githubusercontent.com/6970715/79420228-184d9080-7feb-11ea-8688-443a0d2a2ca7.png">

### GitHub Actionsにおける制約

<img width="1271" alt="スクリーンショット 2020-04-16 14 04 41" src="https://user-images.githubusercontent.com/6970715/79420292-3d420380-7feb-11ea-9833-f257bd01859b.png">

GitHub ActionsではGitHubが提供するハードウェア上でプログラムを実行する、**いわゆるクラウド型のサービス**だ。どういったハードウェアでプログラムが実行されるかについて詳しくは公開されていないものの、ある程度の情報はドキュメント内で言及されている。これによると、**LinuxおよびWindows環境の仮想マシンについてはMicrosoftのクラウドサービスであるAzureを使って提供されており**、マシンスペックはStandard_DS2_v2（仮想CPU×2、メモリ7GB、ストレージ14GB）だという。また、macOS環境についてはMacStadiumというmacOS環境をホスティングするサービスを使って提供しているとのことだ。

## GitHub Actionsで簡単なCI/CDを実行する

GitHub Actionsでは、**さまざまな言語向けにビルドやテストを行うための設定を記述したワークフローが提供されている**。**ビルドやテストの自動化を行うだけであれば、多くの場合それらを利用するだけで簡単にCIが実現できる**。ただ、**独自の処理を実行させたい場合や、ビルドに独自の手順が必要なものの場合は自前でワークフローを定義する必要がある**。以下では、独自のワークフローの記述方法や記述できる内容を説明していこう。

GitHub Actionsでは、**前述のとおり実行する処理や実行する条件などをYAML形式（拡張子は「.yml」もしくは「.yaml」）のファイルに記述することでワークフローを定義する。**このファイルは、リポジトリのルートディレクトリ直下にある**.github/workflowsディレクトリ内に作成する必要がある**。このファイルに記述すべき内容についてはWorkflow syntax for GitHub Actionsというドキュメントにまとめられているが、まず必須となっているのが「**on**」および「**runs-on**」という2つの要素だ。

サンプル
```
# This is a basic workflow to help you get started with Actions
name: Bob Github Actions test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: print helloworld
      run: echo HELLO GITHUB ACTIONS by $OWNER
      env:
        OWNER: WANG BO
    - name: print path
      run: echo $GITHUB_WORKSPACE
    - name: javac HelloWorld.java
      run: |
       javac $GITHUB_WORKSPACE/src/com/bob/github/actions/Hello_Github_Actions.java
       ls -la $GITHUB_WORKSPACE/src/com/bob/github/actions/Hello_Github_Actions.class
       echo "javac Success!"
    - name: java HelloWorld
      run: java com.bob.github.actions.Hello_Github_Actions
      working-directory: /home/runner/work/Hello_Github_Actions/Hello_Github_Actions/src
```

まず**on要素だが、これはワークフローを起動するトリガーとなるイベント**、もしくはワークフローを起動する時刻を記述するものだ。たとえばリポジトリへのプッシュが行われた際にワークフローを起動したい場合、次のように「push」を指定する。

<img width="611" alt="スクリーンショット 2020-04-16 14 05 12" src="https://user-images.githubusercontent.com/6970715/79420343-53e85a80-7feb-11ea-8c9e-c72d706ff316.png">

ここで指定できるイベントは、Events that trigger workflowsドキュメントやEvents that trigger workflowsにて解説されているが、**GitHubのWebhook機能で定義されているイベントと同一のものが指定できるようになっている**。そのため、リポジトリへのプッシュ（「push」）やブランチもしくはタグの作成および削除（「create」および「delete」）といったGitリポジトリを対象とした操作だけでなく、たとえばプルリクエストやissuesの作成（「pull_request」および「issues」）、issuesへのコメント投稿（「issue_comment」）、リポジトリのフォーク（「fork」）、Wikiページの作成（「gollum」）といった、GitHub特有の機能をトリガーとしてワークフローを起動することもできるようになっている。

「on」要素はリスト形式で**複数のイベントを指定することもできる**。たとえば「create」と「delete」の両方のイベントに対応したい場合、次のように指定すれば良い。

<img width="615" alt="スクリーンショット 2020-04-16 14 05 18" src="https://user-images.githubusercontent.com/6970715/79420361-5ba7ff00-7feb-11ea-8401-d53981931b01.png">

### アクティビティの種類もしくは設定を伴う複数のイベントを使用する例
<img width="609" alt="スクリーンショット 2020-04-16 14 05 52" src="https://user-images.githubusercontent.com/6970715/79420427-767a7380-7feb-11ea-9622-c870e1e61ce9.png">
<img width="614" alt="スクリーンショット 2020-04-16 14 05 59" src="https://user-images.githubusercontent.com/6970715/79420432-78dccd80-7feb-11ea-9b40-f988a8e2574f.png">
<img width="744" alt="スクリーンショット 2020-04-16 14 06 11" src="https://user-images.githubusercontent.com/6970715/79420435-7a0dfa80-7feb-11ea-9c79-00d037659b82.png">

on.<event_name>.types
**ワークフローの実行をトリガーする特定のアクティビティ**。 ほとんどの GitHub イベントは、2 つ以上のアクティビティタイプからトリガーされます。 たとえば、releaseリソースに対するイベントは、release が published、unpublished、created、edited、deleted、または prereleased の場合にトリガーされます。 typesキーワードを使用すると、ワークフローを実行させるアクティブの範囲を狭くすることができます。

<img width="604" alt="スクリーンショット 2020-04-16 14 06 57" src="https://user-images.githubusercontent.com/6970715/79420460-8db96100-7feb-11ea-864b-d2242995dfc7.png">

**特定のブランチやタグのみを対象に指定することも可能**だ。この場合、「*」や「**」といったワイルドカードを使用して対象のブランチやタグを指定することもできる。たとえば「master」ブランチと「foo」で始まるブランチへのプッシュのみを対象にしたい場合、次のように記述する。

<img width="606" alt="スクリーンショット 2020-04-16 14 07 13" src="https://user-images.githubusercontent.com/6970715/79420484-9742c900-7feb-11ea-91aa-7e0ab399b864.png">

pushおよびpull_requestイベントを使用する場合、特定のブランチまたはタグで実行するワークフローを設定できます。 pull_requestでは、ベース上のブランチ及びタグだけが評価されます。 tagsもしくはbranchesだけを定義すると、定義されていないGit refに影響するイベントに対して、ワークフローが実行されません。

branches、branches-ignore、tags、および tags-ignoreのキーワードは、\*と\*\*のワイルドカード文字を使って複数のブランチやタグ名と一致させるglobパターンを受け付けます

<img width="601" alt="スクリーンショット 2020-04-16 14 07 36" src="https://user-images.githubusercontent.com/6970715/79420512-a45fb800-7feb-11ea-9ae1-3c5675fd04f8.png">

**ブランチとタグを無視する例**
<img width="606" alt="スクリーンショット 2020-04-16 14 08 00" src="https://user-images.githubusercontent.com/6970715/79420545-b3466a80-7feb-11ea-9bfa-cc2e2077e2a9.png">

on.<push|pull_request>.paths
push および pull_request イベントを使用する場合、1 つ以上の変更されたファイルが paths-ignore にマッチしない場合や、1 つ以上の変更されたファイルが、設定された paths にマッチする場合にワークフローを実行するように設定できます。 タグへのプッシュに対して、パスのフィルタは評価されません。

<img width="606" alt="スクリーンショット 2020-04-16 14 08 23" src="https://user-images.githubusercontent.com/6970715/79420567-c0635980-7feb-11ea-98f8-431ff7aabfed.png">

特定のイベントではなく、**決まった日、時刻にワークフローを実行させたい場合は、「on.schedule」要素で日時の指定を行う**。ここではUNIX（POSIX）のcronと同じ形式（「<分> ＜時＞ ＜日＞ ＜月＞ ＜曜日＞」という形式）で日時の指定が可能だ。たとえば毎時30分にワークフローを実行したい場合、次のように記述する。

<img width="614" alt="スクリーンショット 2020-04-16 14 08 42" src="https://user-images.githubusercontent.com/6970715/79420598-cc4f1b80-7feb-11ea-9eb6-0807e02b39aa.png">

必須要素の2つ目は、**ワークフローを実行する仮想マシン環境を指定する「runs-on」要素**だ。記事執筆時で選択できる値は表3のとおりとなっている。

<img width="608" alt="スクリーンショット 2020-04-16 14 09 24" src="https://user-images.githubusercontent.com/6970715/79420642-e557cc80-7feb-11ea-9e83-8562e218a3df.png">

**ユーザーが独自に用意した実行環境でワークフローを実行する方法**については、
https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners
を参照してください。

また、必須ではないがワークフローに対しては次のように「name」要素で名前を、「env」要素で環境変数を指定することもできる。

<img width="612" alt="スクリーンショット 2020-04-16 14 09 44" src="https://user-images.githubusercontent.com/6970715/79420672-f6a0d900-7feb-11ea-9c8b-0d5aea6efad3.png">

**ここで指定した環境変数は、このワークフローで定義されたすべての処理の実行時に指定されたプログラムに渡される**。

<img width="612" alt="スクリーンショット 2020-04-16 14 09 49" src="https://user-images.githubusercontent.com/6970715/79420677-fc96ba00-7feb-11ea-9521-aa9244d3576f.png">

ただし、**これらはあくまで環境変数であり、処理の実行時にしか参照できない**。ワークフロー内の各種要素を記述する際に変数的なものを利用したい場合は、後述する「コンテキスト」機能を利用することになる。

なお、GitHub Actionsではデフォルトでいくつかの環境変数を定義する。定義されている環境変数についてはUsing environment variablesドキュメントを参照してほしい。
https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables

<img width="691" alt="スクリーンショット 2020-04-16 14 10 46" src="https://user-images.githubusercontent.com/6970715/79420742-1f28d300-7fec-11ea-964b-b1ddd8f817c9.png">
<img width="679" alt="スクリーンショット 2020-04-16 14 10 51" src="https://user-images.githubusercontent.com/6970715/79420753-23ed8700-7fec-11ea-8782-62e9e9ea88dc.png">
<img width="1262" alt="スクリーンショット 2020-04-16 14 10 56" src="https://user-images.githubusercontent.com/6970715/79420760-2819a480-7fec-11ea-9054-e4eaceefa614.png">

## 実行する処理内容の記述

実行する処理（ジョブ）は、ワークフロー内の「jobs」要素以下で記述する。jobs要素では次のような形式で複数を指定できる。ここで「ジョブID」はジョブを参照する際などに使われる一意な文字列で、「ジョブ名」は管理画面などに表示される名前として使われる文字列だ。

<img width="620" alt="スクリーンショット 2020-04-16 14 11 30" src="https://user-images.githubusercontent.com/6970715/79420810-3ebffb80-7fec-11ea-95c9-f2e833d75f22.png">

GitHub Actionsでは、定義されたジョブは基本的に並列に実行される。もし特定の順序でジョブを実行したい場合、「jobs.＜ジョブID＞.needs」要素でジョブの依存性を定義する。たとえば「bar」というジョブを「foo」というジョブの完了後に実行したい場合、次のように記述する。

<img width="613" alt="スクリーンショット 2020-04-16 14 11 36" src="https://user-images.githubusercontent.com/6970715/79420823-44b5dc80-7fec-11ea-87c3-facebb62d803.png">

各ジョブで実行する処理は、次のように「**steps**」要素で記述する。

<img width="614" alt="スクリーンショット 2020-04-16 14 11 41" src="https://user-images.githubusercontent.com/6970715/79420835-4a132700-7fec-11ea-88bb-7c0e14249d02.png">

**steps要素はオブジェクトのリストとなっており、指定された順序で処理が実行される。**ここでは「name」要素で処理内容を示す名前を、「**run**」**要素で実行するコマンドを指定する**。ちなみに**run要素で指定したコマンドはシェル経由で実行されるようになっており**、実行環境が非Windowsプラットフォームの場合はbash（bashが存在しない場合はsh）、Windowsプラットフォームの場合はPowerShellがデフォルトのシェルとして使われる。「shell」要素で明示的に使用するシェルを指定することも可能だ。たとえばGitHubが提供するWindows環境ではGit for Windowsと一緒にbashがインストールされているので、次のように明示的に指定することでWindows環境でもbashを使ってコマンドを実行できる。

<img width="616" alt="スクリーンショット 2020-04-16 14 12 43" src="https://user-images.githubusercontent.com/6970715/79420885-5d25f700-7fec-11ea-8787-7433e66504df.png">

**run要素では複数行のコマンドを指定することもできる**。これはYAMLの「ブロックスタイル」式の記述を行うための「|」記号を使えば良い。

<img width="569" alt="スクリーンショット 2020-04-16 14 13 17" src="https://user-images.githubusercontent.com/6970715/79420947-762ea800-7fec-11ea-95da-7d0c0d9bd856.png">
<img width="1282" alt="スクリーンショット 2020-04-16 14 13 24" src="https://user-images.githubusercontent.com/6970715/79420954-78910200-7fec-11ea-9053-ee3bbf63883e.png">

working-directoryキーワードを使えば、コマンドが実行されるワーキングディレクトリを指定できます。
<img width="616" alt="スクリーンショット 2020-04-16 14 13 55" src="https://user-images.githubusercontent.com/6970715/79420992-89417800-7fec-11ea-84e0-d51abeaf28ea.png">

また、steps以下ではrun要素ではなく「**uses**」要素を指定することで、**任意の通常なActionを実行できる**、**Actionに与えるパラメータ（引数）は「with」要素で指定する。**

<img width="613" alt="スクリーンショット 2020-04-16 14 14 27" src="https://user-images.githubusercontent.com/6970715/79421038-9b231b00-7fec-11ea-8aac-7e5bb5d44f3b.png">

多くの場合、**使用するActionのドキュメントにuses要素やwith要素で指定するパラメータについて記載されているはず**なので、基本的にはそれに従えば良い。たとえばリポジトリからのチェックアウトを行う「actions/checkout」というActionを利用して、リポジトリ内の「foo」というブランチをチェックアウトする場合、次のように記述する。

<img width="615" alt="スクリーンショット 2020-04-16 14 14 51" src="https://user-images.githubusercontent.com/6970715/79421082-a7a77380-7fec-11ea-8377-2435ac6b285f.png">

なお、usesを指定する場合、「name」要素による名前の指定は省略されることが多い。その場合、Action名が名前として指定されたことになる。

### 引用 action

**每一个action，就是一个通用的动作单元**

- 引用公有库中的 action
引用 action 的格式是 {owner}/{repo}@{ref} 或 {owner}/{repo}/{path}@{ref} ，
比如 actions/checkout@v1 ，你还可以使用标准库中的其它 action ，如设置 node 版本:

<img width="611" alt="スクリーンショット 2020-04-16 14 15 14" src="https://user-images.githubusercontent.com/6970715/79421110-b55cf900-7fec-11ea-8254-56faa57e9b8c.png">

- 引用同一个库中的 action
引用格式：{owner}/{repo}@{ref} 或 ./path/to/dir 。

<img width="607" alt="スクリーンショット 2020-04-16 14 15 43" src="https://user-images.githubusercontent.com/6970715/79421146-c6a60580-7fec-11ea-8e8a-2dc7ddbd4eea.png">

- 引用 Docker Hub 上的 container
如果某个 action 定义在了一个 docker container image 中且推送到了 Docker Hub 上，你也可以引入它，格式是 docker://{image}:{tag} ，示例：

<img width="616" alt="スクリーンショット 2020-04-16 14 16 10" src="https://user-images.githubusercontent.com/6970715/79421181-db829900-7fec-11ea-8f59-4ccc5a3f0303.png">

uses要素で「docker://＜イメージ名＞:＜タグ＞」を指定する。このとき、with要素の「entrypoint」要素や「args」要素でコンテナを実行する際のエントリーポイントや引数を指定できる。

<img width="618" alt="スクリーンショット 2020-04-16 14 16 16" src="https://user-images.githubusercontent.com/6970715/79421190-e2111080-7fec-11ea-833f-892f93c05f39.png">

## 複数のステップで共有するコンテナを立ち上げる

**ジョブ全体を特定のコンテナ内で実行させることも可能**だ。これは、「jobs.＜ジョブID＞.container」要素でコンテナを指定することで行える。

jobs.<job_id>.container
containerを設定しない場合は、コンテナで実行されるよう設定されているアクションを参照しているステップを除くすべてのステップが、runs-onで指定したホストで直接実行されます。

<img width="618" alt="スクリーンショット 2020-04-16 14 16 51" src="https://user-images.githubusercontent.com/6970715/79421213-efc69600-7fec-11ea-9393-d1a2f5127c9d.png">

ここで「env」要素はコンテナ実行時に与える環境変数を、「ports」要素は待ち受けを行うポート番号を、「volumes」要素はコンテナ内にマウントするボリュームを指定するもので、それぞれdockerコマンドの「-e」および「-p」「-v」オプションに相当する。指定方法もdockerコマンドの場合とほぼ同じだ。また、「options」要素で任意のオプションを指定することも可能だ。

このように指定されたジョブでは、その各ステップにおいてコンテナが明示的に指定されない限り、**ここで指定したコンテナ内で各ステップの処理が実行される。**

## 各ステップとは並列に動作するコンテナを立ち上げる

テスト用のWebサーバーやデータベースなど、各ステップで処理を実行するコンテナとは別にコンテナが必要となる場合がある。その場合、**jobs.＜ジョブID＞.services要素で各ステップとは独立して動作するコンテナを立ち上げるよう指定できる。**

ここでは先ほどの「container」要素と同じようなパラメータを指定可能だ。

<img width="618" alt="スクリーンショット 2020-04-16 14 17 13" src="https://user-images.githubusercontent.com/6970715/79421245-0371fc80-7fed-11ea-9f48-754ca29d9732.png">

```
name: Redis container example
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci

      - name: Connect to Redis
        # Runs a script that creates a Redis client, populates
        # the client with data, and retrieves data
        run: node client.js
        # Environment variable used by the `client.js` script to create a new Redis client.
        env:
          # Redisサービスコンテナとの通信に使われるホスト名
          REDIS_HOST: redis
          # デフォルトのRedisポート
          REDIS_PORT: 6379
```

コンテナジョブの設定
このワークフローはnode:10.18-jessieコンテナ内で実行されるジョブを設定し、ubuntu-latest GitHubホストランナーをコンテナ用のDockerホストとして使用します。

ワークフローはredisというラベルでサービスコンテナを設定します。 すべてのサービスはコンテナ内で実行しなければならないので、各サービスについてコンテナのイメージを指定しなければなりません。

ワークフローは以下のステップを実行します。

1. ランナー上にリポジトリをチェックアウト
2. 依存関係のインストール
3. クライアントを作成するスクリプトの実行

Redisサービスのホスト名は、ワークフロー中で設定されたラベルで、ここではredisです。 同じユーザー定義ブリッジネットワーク上のDockerコンテナは、デフォルトですべてのポートをオープンするので、サービスコンテナにはデフォルトのRedisのポートである6379でアクセスできます。

## パラメータを変数で指定する

ワークフローの実行時には、そのワークフローのトリガーとなったコミットやさまざまな実行時情報が「**コンテキスト**」としてワークフローに与えられる。**これらの情報については、「${{ ＜コンテキスト名＞ }}」のように記述することで実行時にアクセスできる。**

<img width="606" alt="スクリーンショット 2020-04-16 14 17 51" src="https://user-images.githubusercontent.com/6970715/79421290-12f14580-7fed-11ea-869b-76cb2277909d.png">

たとえば、「${{ github.sha }}」という文字列は、実行時にはそのワークフローの実行のトリガとなったコミットのハッシュ文字列に置き換えられる。

## プラットフォームやバージョンを変えながら同じ処理を実行する「build matrix」

**異なるバージョンや複数のプラットフォームを対象としたテストやパッケージのビルド**を行う場合、それらをいちいち個別のジョブとして定義するのは面倒だ。この問題に対応するため、ワークフローでは「**build matrix**」という機能が用意されている。これは、あらかじめ繰り返しの際に変更したいパラメータを定義しておくことで、そのパラメータを変えながら順に処理を実行するという機能だ。**変更したいパラメータは「strategy.matrix」という要素で定義できる。**

たとえば、次のように定義することで指定したActionに対し「version」というパラメータを「1」「2」「3」と変更しながら3回実行させることができる。

<img width="608" alt="スクリーンショット 2020-04-16 14 18 11" src="https://user-images.githubusercontent.com/6970715/79421312-1edd0780-7fed-11ea-8f00-5bdeef3df36d.png">

また、プラットフォームを変えながら複数回実行したい場合は「os」というパラメータをmatrix以下で指定すれば良い。

<img width="610" alt="スクリーンショット 2020-04-16 14 18 40" src="https://user-images.githubusercontent.com/6970715/79421345-31574100-7fed-11ea-8773-c028786b4f77.png">

この場合、steps要素で定義されたActionがUbuntu 16.04環境と18.04環境でそれぞれ実行される。

matrix要素以下では複数のパラメータを指定することもできる。その場合、それらパラメータのすべての組み合わせについて繰り返しActionが実行される。たとえば次のように指定すると、Ubuntu 16.04環境と18.04環境の両方で「version」引数にそれぞれ1、2、3を与えてActionが実行される。

<img width="612" alt="スクリーンショット 2020-04-16 14 19 10" src="https://user-images.githubusercontent.com/6970715/79421378-42a04d80-7fed-11ea-916f-5a71f30ed116.png">

**GitHub Actionsではワークフローの実行毎にワークフローを実行する仮想マシンが作成され、実行完了後にはその仮想マシンは削除される。**

## Docker コンテナのアクションを作成する

https://help.github.com/ja/actions/building-actions/creating-a-docker-container-action

## 最简单的Golang CI

<img width="612" alt="スクリーンショット 2020-04-16 14 19 37" src="https://user-images.githubusercontent.com/6970715/79421411-52b82d00-7fed-11ea-860c-1915abd244b0.png">

## 公開サイト

https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
